const actionType = {
  // auth
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  ADD_TOAST_MESSAGE: "ADD_TOAST_MESSAGE",
  // message
  REMOVE_TOAST_MESSAGE: "REMOVE_TOAST_MESSAGE",
  HANDLE_INVALID_PARAMETER: "HANDLE_INVALID_PARAMETER",
  HANDLE_NOT_FOUND: "HANDLE_NOT_FOUND",
  HANDLE_SERVER_ERROR: "HANDLE_SERVER_ERROR",
  // item
  LOADING_SHOW: "LOADING_SHOW",
  LOADING_HIDE: "LOADING_HIDE",
  ADD_ITEM_IMAGE: "ADD_ITEM_IMAGE",
  FETCH_ITEM: "FETCH_ITEM",
  FETCH_ITEM_FULFILLED: "FETCH_ITEM_FULFILLED",
  SUBMIT_ITEM: "SUBMIT_ITEM",
  SUBMIT_ITEM_FULFILLED: "SUBMIT_ITEM_FULFILLED",
  DELETE_ITEM: "DELETE_ITEM",
  DELETE_ITEM_FULFILLED: "DELETE_ITEM_FULFILLED",
  DELETE_ITEM_IMAGE: "DELETE_ITEM_IMAGE",
  DELETE_ITEM_IMAGE_FULFILLED: "DELETE_ITEM_IMAGE_FULFILLED",
  SET_ITEM_SEARCH_KEYWORD: "SET_ITEM_SEARCH_KEYWORD",
  SET_FORM_TITLE: "SET_FORM_TITLE",
  SET_ITEM_FORM: "SET_ITEM_FORM",
  SET_ITEM_FORM_ERRORS: "SET_ITEM_FORM_ERRORS",
  SET_ITEM_TITLE: "SET_ITEM_TITLE",
  SET_ITEM_DESCRIPTION: "SET_ITEM_DESCRIPTION",
  SET_ITEM_PRICE: "SET_ITEM_PRICE",
  SET_ITEM_IMAGE: "SET_ITEM_IMAGE",
  SET_ITEM_IMAGE_URL: "SET_ITEM_IMAGE_URL",
  SET_DELETE_ITEM_ID: "SET_DELETE_ITEM_ID",
  TOGGLE_ITEM_FORM: "TOGGLE_ITEM_FORM",
  TOGGLE_DELETE_DIALOG: "TOGGLE_DELETE_DIALOG",
  SHOW_ITEM_MENU: "SHOW_ITEM_MENU",
  HIDE_ITEM_MENU: "HIDE_ITEM_MENU",
  DISABLED_LOADING: "DISABLED_LOADING",
  INITIAL_ITEM_FORM: "INITIAL_ITEM_FORM"
};

export default actionType;
